#pragma once

enum render_tag {
	RTAG_TERRAIN = 0b000001,
	RTAG_DYNAMIC_OBJECT = 0b000010,
	RTAG_STATIC_OBJECT = 0b000100,
	RTAG_LIGHT = 0b001000,
	RTAG_REFLECTION = 0b010000,
	RTAG_END
};
enum tag {
	TAG_DEFAULT,
	TAG_TERRAIN,
	TAG_SPACE,
	TAG_STATIC_OBJECT,
	TAG_DYNAMIC_OBJECT,
	TAG_LIGHT,
	TAG_REFLECTION,
	TAG_SSRF,
	TAG_SSLR,
	TAG_POSTPROCESSING,
	TAG_DEBUG,
	TAG_END
};

enum shader_value_num {
	SVN_DEFAULT,
	SVN_DEBUG,
	SVN_END
};

enum SCENE_ID
{
	SC_LOBBY,
	SC_HEROSEL,
	SC_ORITOWN,	
	SC_REPAIRTOWN,
	SC_ALDENAD,
	SC_BOSS,
	SC_FINAL,
	SC_END
};


enum ELF_ANIMSTATE
{
	ELF_ANIM_IDLE,
	ELF_ANIM_WPREADY,
	ELF_ANIM_DIE,
	ELF_ANIM_DEADBODY,
	ELF_ANIM_JUMP_START,
	ELF_ANIM_JUMP_LOOP,
	ELF_ANIM_JUMP_END,
	ELF_ANIM_RUN_F,
	ELF_ANIM_RUN_B,
	ELF_ANIM_RUN_L,
	ELF_ANIM_RUN_R,
	ELF_ANIM_RUN_FL,
	ELF_ANIM_RUN_FR,
	ELF_ANIM_RUN_BL,
	ELF_ANIM_RUN_BR,
	ELF_ANIM_RUN_FSTOP,
	ELF_ANIM_JUMP_F_START,
	ELF_ANIM_JUMP_F_LOOP,
	ELF_ANIM_JUMP_F_END,
	ELF_ANIM_JUMP_B_START,
	ELF_ANIM_JUMP_B_LOOP,
	ELF_ANIM_JUMP_B_END,
	ELF_ANIM_HIT_F,
	ELF_ANIM_HIT_B,
	ELF_ANIM_HITDOWN_START,
	ELF_ANIM_HITDOWN_LOOP,
	ELF_ANIM_HITDOWN_END,
	ELF_ANIM_HITDOWN_BOUNCE,
	ELF_ANIM_HITDOWN_GETUP,
	ELF_ANIM_ATTACK,
	ELF_ANIM_SKILL1_CHARGING,
	ELF_ANIM_SKILL1_FIRE,
	ELF_ANIM_END
};